### PR TITLE
feat: allow to disable metric sort

### PR DESCRIPTION
**Pull request by simPod**
This function does 50 % of a loading time (using inmemory adapter) so I'd like to be able to disable it.

### CODE REVIEW

**Comment by simPod** [comment]
disabling sort reduced the scrape duration by half

image

**Comment by LKaemmerling** [comment]
Hey @simPod,

good catch! I'm thinking of don't sort it per default. What do you think? Of course this would be a bit different to what the other libs do (go/python) however it seems the sorting there is more efficent.

**Comment by simPod** [comment]
Yup but that would be BC. We can introduce this flag and flip the default value in next major? Your call.

**Comment by LKaemmerling** [comment]
Thank you!

**Comment by javespi** [comment]
Hello!

> Yup but that would be BC. We can introduce this flag and flip the default value in next major? Your call.

I think it's still BC for any class which implements `RegistryInterface`. Use cases like mocks or wrappers.

After the latest minor release I am having this error:

```
PHP Fatal error:  Declaration of Javespi\MyCollectorRegistry::getMetricFamilySamples(): array must be compatible with Prometheus\RegistryInterface::getMetricFamilySamples(bool $sortMetrics = true): array
```

I think the only way of being BC is removing the type hint of the argument. I'll try to create a pull-request with a hotfix for this.

**Pull request merged**
