### PR TITLE
Feat/add summary support

### PR DESCRIPTION
**Pull request by mp3000mp**
Hi, 

Here is my contribution to this great library to support summary type (see #6 ).

Also, it's out of subject but I wonder if this is really userfull to maintain the InMemoryAdapter ? I don't see any use case for this one.

I'm afraid it's quite a big MR so good luck for the review ;)

### CODE REVIEW

**Comment by LKaemmerling** [comment]
Really Great MR! For me, it looks totally fine on the first view. I started the tests and will then look when they are ready.

For the InMemoryAdapter:
This one is quite useful when you always want to generate the latest response. I use it in most of my projects.

**Comment by mp3000mp** [comment]
Hi @menkaff, it seems that it's not a trivial implementation for me so I suggest to keep this PR as simple as possible and open a new enancement issue for [Cormode, Korn, Muthukrishnan, and Srivastava targeted high-percentile epsilon-approximate
quantiles](http://dimacs.rutgers.edu/~graham/pubs/papers/bquant-icde.pdf) support.
Let's just go step by step ?

@LKaemmerling, thanks and fair enough for the InMemoryAdapter ;)

**Comment by menkaff** [comment]
@mp3000mp Thanks for this PR I'm using it, and You are right targeted percentile is really hard :)

**Comment by mp3000mp** [comment]
Hi @LKaemmerling, do you have any news about this PR ?

**Comment by LKaemmerling** [comment]
Hey @mp3000mp,
Im currently on vacation. I had a short look over the code and it looks fine for me, good job! I will be back next week and then test it out further.

**Review by LKaemmerling — APPROVED** [review]
I tested it out and this looks really great! Good job!

**Comment by zwick** [comment]
This release caused a breaking change due to the change to the `Adapter` interface with the addition of the `updateSummary` method. It looks like this also happened with 2.2.2 ([issue link](https://github.com/PromPHP/prometheus_client_php/issues/43)). Any additions to an Interface are going to break existing implementations.

Please consider changes like this when increasing the package version number to adhere to the basics of semantic versioning. Thankfully, in my case the change was pretty easy to find and fix with our implementation

Thank you for all the work you do to maintain this package!

**Comment by LKaemmerling** [comment]
> This release caused a breaking change due to the change to the `Adapter` interface with the addition of the `updateSummary` method. It looks like this also happened with 2.2.2 ([issue link](https://github.com/PromPHP/prometheus_client_php/issues/43)). Any additions to an Interface are going to break existing implementations.
> 
> Please consider changes like this when increasing the package version number to adhere to the basics of semantic versioning. Thankfully, in my case the change was pretty easy to find and fix with our implementation
> 
> Thank you for all the work you do to maintain this package!

Hey @zwick,

the (Storage) Adapter Interface is not meant to be used by client applications is therefore not part of the Semver Versioning.  Only the registry (& those methods) are part of the promise.

**Comment by zwick** [comment]
@LKaemmerling Sorry, I misread the original reply you gave in that issue where you explained this. This seems like an issue with my specific implementation since we were using the Adapter directly.

Thanks again for maintaining this package

**Pull request merged**
